### ISSUE TITLE
Subclass IDZAQAudioPlayer in Swfit retains the player and decoder

### ISSUE THREAD

**Issue by zwang** [iosdevzone/IDZAQAudioPlayer#5]
Hi thanks for this library. I am trying to use this in my project, and got a weird issue. 

I have a swift class subclassing IDZAQAudioPlayer. And I created a pool of these players. However, after the players being used, there is always exact one player left in memory, and the player is holding reference to the decoder too. I could not figure out what retains the reference. However, as long as remove IDZAQAudioPlayer from the code and implement the dummy functions there, then the memory get released correctly. Here is the subclass:

    class PlaOggAudioPlayer: IDZAQAudioPlayer, PlaAudioPlayer {
        private var lastPlayedTime: NSDate
        internal var isOriginal: Bool

        init(audioFilePath: String, isOriginal: Bool = false) throws {
            lastPlayedTime = NSDate()
            self.isOriginal = isOriginal
            let url = NSURL(fileURLWithPath: audioFilePath)
            let decoder = try! IDZOggVorbisFileDecoder(contentsOfURL: url)
            try super.init(decoder: decoder)
        }

        var numberOfLoops = 0
        var pan: Float = 0
        var volume: Float = 1
        var rate: Float = 1

        override func play() -> Bool {
            lastPlayedTime = NSDate()
            return super.play()
        }

        func inactiveForMoreThanMinutes(minutes: Int) -> Bool {
            let now = NSDate()
            let inactiveTimeInSecs = now.timeIntervalSinceDate(lastPlayedTime)
            return inactiveTimeInSecs >= Double(minutes * 60)
        }
    }

    protocol PlaAudioPlayer {
    var isOriginal: Bool { get set }
    var playing: Bool { get }
    var numberOfLoops: Int { get set }
    var pan: Float { get set}
    var volume: Float { get set }
    var rate: Float { get set }

    func inactiveForMoreThanMinutes(minutes: Int) -> Bool
    func play() -> Bool
    func prepareToPlay() -> Bool
    }

**Comment by iosdevzone** [comment]
Hi zwang, sorry you ran into some problems. Looks like there might need to be a dealloc added to the `IDZAQAudioPlayer` to delete the `AudioQueue` and buffers. This would not explain why you see exactly one remaining instance. It could be a little while until I get to investigate this fully. Do you have a small sample app you can share the source of? This would really speed things up.

**Comment by zwang** [comment]
Hi @iosdevzone 

Thank you for the help. I will try explicitly dealloc first. And if it does not solve the problem, I will set up a small project to demo the bug. Thank you again for your help.

**Comment by zwang** [comment]
Hi @iosdevzone,

I created a demo project to investigate this issue. It turns out this is more a problem at my size. It is not related to your code. Your code works well. I will close this issue as a false alert.  

Thank you very much for the help. Appreciate it. :+1:

**Comment by iosdevzone** [comment]
You're very welcome. Please let me know if you find any other issues with the library.
